// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XActBackend.Persistence.Util;

#nullable disable

namespace XActBackend.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260608155236_AddReportKickVotingAndOffenses")]
    partial class AddReportKickVotingAndOffenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("XActBackend")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XActBackend.Persistence.Model.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SenderMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("SenderTeamId")
                        .HasColumnType("integer");

                    b.Property<Instant>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SenderMemberId");

                    b.HasIndex("TeamId");

                    b.HasIndex("SessionId", "TeamId", "SentAt", "Id")
                        .IsDescending(false, false, true, true);

                    b.ToTable("ChatMessage", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostUserId")
                        .HasColumnType("integer");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("MrXRevealInterval")
                        .HasColumnType("integer");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Instant?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("GameSession", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.GeofencePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GeofencePoint", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.KickVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InitiatorMemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorMemberId");

                    b.HasIndex("TargetMemberId");

                    b.HasIndex("SessionId", "Status");

                    b.ToTable("KickVote", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.KickVoteBallot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approve")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CastAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KickVoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("VoterMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VoterMemberId");

                    b.HasIndex("KickVoteId", "VoterMemberId")
                        .IsUnique();

                    b.ToTable("KickVoteBallot", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.LocationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsRevealedPosition")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<Instant>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("LocationLog", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.Offense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant?>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Status");

                    b.HasIndex("MemberId", "Type", "Status");

                    b.ToTable("Offense", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.PowerUpUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("PowerUpType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("PowerUpUsage", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsCaught")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Team", "XActBackend", t =>
                        {
                            t.HasCheckConstraint("CK_Team_MaxPlayerCount_Positive", "\"MaxPlayerCount\" > 0");
                        });
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("GuestName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsTeamLeader")
                        .HasColumnType("boolean");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SessionId", "UserId")
                        .IsUnique();

                    b.HasIndex("TeamId", "GuestName")
                        .IsUnique();

                    b.ToTable("TeamMember", "XActBackend", t =>
                        {
                            t.HasCheckConstraint("CK_TeamMember_UserOrGuest", "(\"UserId\" IS NOT NULL AND \"GuestName\" IS NULL) OR (\"UserId\" IS NULL AND \"GuestName\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.UserAuthIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderSubject")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAuthIdentity", "XActBackend");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.ChatMessage", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Sender");

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.GameSession", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.User", "Host")
                        .WithMany("HostedSessions")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.GeofencePoint", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany("GeofencePoints")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.KickVote", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "InitiatorMember")
                        .WithMany()
                        .HasForeignKey("InitiatorMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "TargetMember")
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InitiatorMember");

                    b.Navigation("Session");

                    b.Navigation("TargetMember");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.KickVoteBallot", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.KickVote", "KickVote")
                        .WithMany("Ballots")
                        .HasForeignKey("KickVoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KickVote");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.LocationLog", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "Member")
                        .WithMany("LocationLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.Offense", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.PowerUpUsage", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.TeamMember", "Member")
                        .WithMany("PowerUpUsages")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.Team", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany("Teams")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.TeamMember", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.GameSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XActBackend.Persistence.Model.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.UserAuthIdentity", b =>
                {
                    b.HasOne("XActBackend.Persistence.Model.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.GameSession", b =>
                {
                    b.Navigation("GeofencePoints");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.KickVote", b =>
                {
                    b.Navigation("Ballots");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.TeamMember", b =>
                {
                    b.Navigation("LocationLogs");

                    b.Navigation("PowerUpUsages");
                });

            modelBuilder.Entity("XActBackend.Persistence.Model.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("HostedSessions");

                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
