name: xact_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  signalr_netcore: ^1.4.4
  url_launcher: ^6.3.1
  uni_links: ^0.5.1
  flutter_secure_storage: ^10.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  qr_flutter: ^4.1.0
  share_plus: ^12.0.2
  mobile_scanner: ^7.0.0
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
