name: Flutter Build

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.7"
          channel: "stable"

      - name: Get dependencies
        working-directory: xact_frontend
        run: flutter pub get

      - name: Analyze
        working-directory: xact_frontend
        run: flutter analyze

      - name: Build Web
        working-directory: xact_frontend
        run: flutter build web
