name: Flutter Build

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0" 
          channel: "stable"

      - name: Install Dependencies
        working-directory: xact_frontend
        run: flutter pub get

      - name: Flutter Analyze
        working-directory: xact_frontend
        run: flutter analyze

      - name: Flutter Web Build
        working-directory: xact_frontend
        run: flutter build web
